<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../KeysightScopeApp.Core/KeysightScopeApp.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="KeysightTechnologies.Visa" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
  </ItemGroup>
</Project>
